-- VHDL Entity ece411.ADJ6.generatedInstance
--
-- Created:
--          by - sutrave1.ews (gelib-057-01.ews.illinois.edu)
--          at - 15:21:01 01/25/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ADJ6 IS
   PORT( 
      ADJ6out : OUT    LC3b_word;
      clk     : IN     std_logic;
      index6  : IN     LC3b_index6
   );

END ADJ6 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ADJ6 IS 
BEGIN


END generatedInstance;
