-- VHDL Entity ece411.CacheBlock.symbol
--
-- Created:
--          by - sutrave1.ews (gelib-057-06.ews.illinois.edu)
--          at - 19:16:37 02/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheBlock IS
   PORT( 
      AddressTag       : IN     LC3B_C_TAG;
      CacheLineWrite   : IN     std_logic;
      DATAOUT          : IN     LC3B_word;
      PMDATAIN         : IN     LC3B_OWORD;
      RESET_L          : IN     std_logic;
      index            : IN     LC3b_C_INDEX;
      DataArrayOut     : OUT    LC3B_OWORD;
      DirtyBitArrayOut : OUT    std_logic;
      TagArrayOut      : OUT    LC3B_C_TAG;
      ValidBitArrayOut : OUT    std_logic
   );

-- Declarations

END CacheBlock ;

--
-- VHDL Architecture ece411.CacheBlock.struct
--
-- Created:
--          by - sutrave1.ews (gelib-057-06.ews.illinois.edu)
--          at - 19:16:37 02/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF CacheBlock IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DirtyBitIn    : std_logic;
   SIGNAL DirtyBitWrite : std_logic;


   -- Component Declarations
   COMPONENT DataArray
   PORT (
      Reset_L      : IN     std_logic ;
      DataWrite    : IN     std_logic ;
      Index        : IN     LC3B_C_INDEX ;
      DataIn       : IN     LC3B_OWORD ;
      DataArrayOut : OUT    LC3B_OWORD 
   );
   END COMPONENT;
   COMPONENT DirtyBitArray
   PORT (
      DirtyBitIn       : IN     std_logic;
      DirtyBitWrite    : IN     std_logic;
      RESET_L          : IN     std_logic;
      index            : IN     LC3b_C_INDEX;
      DirtyBitArrayOut : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT TagArray
   PORT (
      Reset_L     : IN     std_logic ;
      TagWrite    : IN     std_logic ;
      Index       : IN     LC3B_C_INDEX ;
      TagIn       : IN     LC3B_C_TAG ;
      TagArrayOut : OUT    LC3B_C_TAG 
   );
   END COMPONENT;
   COMPONENT ValidBitArray
   PORT (
      RESET_L          : IN     std_logic;
      ValidBitIn       : IN     std_logic;
      ValidBitWrite    : IN     std_logic;
      index            : IN     LC3b_C_INDEX;
      ValidBitArrayOut : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : DirtyBitArray USE ENTITY ece411.DirtyBitArray;
   FOR ALL : TagArray USE ENTITY ece411.TagArray;
   FOR ALL : ValidBitArray USE ENTITY ece411.ValidBitArray;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   theDataArray : DataArray
      PORT MAP (
         Reset_L      => RESET_L,
         DataWrite    => CacheLineWrite,
         Index        => index,
         DataIn       => PMDATAIN,
         DataArrayOut => DataArrayOut
      );
   theDirtyBitArray : DirtyBitArray
      PORT MAP (
         DirtyBitIn       => DirtyBitIn,
         DirtyBitWrite    => DirtyBitWrite,
         RESET_L          => RESET_L,
         index            => index,
         DirtyBitArrayOut => DirtyBitArrayOut
      );
   theTagArray : TagArray
      PORT MAP (
         Reset_L     => RESET_L,
         TagWrite    => CacheLineWrite,
         Index       => index,
         TagIn       => AddressTag,
         TagArrayOut => TagArrayOut
      );
   theValidBitArray : ValidBitArray
      PORT MAP (
         RESET_L          => RESET_L,
         ValidBitIn       => CacheLineWrite,
         ValidBitWrite    => CacheLineWrite,
         index            => index,
         ValidBitArrayOut => ValidBitArrayOut
      );

END struct;
