-- VHDL Entity ece411.RegFile.generatedInstance
--
-- Created:
--          by - sutrave1.ews (gelib-057-01.ews.illinois.edu)
--          at - 15:21:01 01/25/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY RegFile IS
   PORT( 
      clk         : IN     std_logic;
      dest        : IN     LC3b_reg;
      RegWrite    : IN     std_logic;
      RESET_L     : IN     std_logic;
      RFAout      : OUT    LC3b_word;
      RFBout      : OUT    LC3b_word;
      RFMuxout    : IN     LC3b_word;
      SrcB        : IN     LC3b_reg;
      StoreMuxout : IN     LC3b_reg
   );

END RegFile ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF RegFile IS 
BEGIN


END generatedInstance;
