-- VHDL Entity ece411.ZEXT10.generatedInstance
--
-- Created:
--          by - sutrave1.ews (gelib-057-23.ews.illinois.edu)
--          at - 14:09:23 02/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ZEXT10 IS
   PORT( 
      clk          : IN     std_logic;
      MDRhigh_byte : IN     LC3b_nibble;
      MDRhigh_word : OUT    LC3b_word
   );

END ZEXT10 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ZEXT10 IS 
BEGIN


END generatedInstance;
