-- VHDL Entity ece411.ZEXT9.generatedInstance
--
-- Created:
--          by - sutrave1.ews (gelib-057-23.ews.illinois.edu)
--          at - 14:09:23 02/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ZEXT9 IS
   PORT( 
      clk         : IN     std_logic;
      MDRlow_byte : IN     LC3b_nibble;
      MDRlow_word : OUT    LC3b_word
   );

END ZEXT9 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ZEXT9 IS 
BEGIN


END generatedInstance;
